a=float(input("Введите координату х1:"))
g=float(input("Введите координату y1:"))
c=float(input("Введите координату х2:"))
d=float(input("Введите координату y2:"))
k=(d-g)/(c-a)
b=g-(k*a)
print(f"у={k}x+{b}")
